language: cpp

services:
  - docker

before_install:
  # Build an image from Dockerfile
  - docker build -t dockerbuild -f tests/Dockerfile .

script:
  # Run build in Docker
  - docker run -e -t -v `pwd`:/usr/local/src/thunderbolt-tools dockerbuild /bin/bash ./tests/docker-build.sh
